# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    ports:
      - "33061:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxx
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: xxxxxxxx
